### ISSUE TITLE
Difficulty name not showing up

### ISSUE THREAD

**Issue by Mozitaka** [FelisCatusKR/LetsSweepSomeMines#2]
![diff](https://user-images.githubusercontent.com/5786243/61367355-66036400-a8c6-11e9-8208-f7598eaababd.PNG)

There are three difficulties at the start screen, EASY and Normal shows up, but the third difficulty (I think it's HARD) is not showing up. Looked up the 'images' folder, there was no image for third difficulty, so I'm guessing that you just didn't add it yet.

My PC spec is
OS : Win10 Pro 64bit Build 17134
Motherboard : B350GT3
CPU : AMD Ryzen 7 1700
Graphics : GTX 1060 3GB

**Comment by FelisCatusKR** [comment]
Thank you for your issue report! It seems that I commited wrong image files which contain no text. I commited new image files and re-uploaded the release build.

**Comment by Mozitaka** [comment]
Just checked it and it's fixed, thank you for your fast response!
